### ISSUE TITLE
Test files in MusicXML will not will not be read into my Finale. 

### ISSUE THREAD

**Issue by mogenslundholm** [w3c/mnxconverter#1]
Test files in MusicXML will not will not read into my Finale version (2012).. 
![image](https://user-images.githubusercontent.com/3636047/82127890-1b3ccc00-97b7-11ea-8994-5dd8c98362e7.png)

PS: Look forward to see more test files.

**Comment by adrianholovaty** [comment]
Thanks Mogens. This was happening because the test MusicXML files didn't have the XML boilerplate (DTD and top-level `<?xml>` tag). Finale is picky and won't accept MusicXML files without this.

I've just added that boilerplate to the MusicXML test files in commit 3667ab3, so Finale will be able to read the files now.

**Comment by mogenslundholm** [comment]
Thanks. 
PS: Shouldn't the MNX-files be Unicode and start with something like FFFE or EFBBBF?

**Comment by adrianholovaty** [comment]
@mogenslundholm The MNX files are indeed encoded as UTF-8.

**Comment by mogenslundholm** [comment]
Thanks. Sounds good. Then I think it is a special Windows problem. I use "clone" and unpack the zip file. Opening the file with Notepad, writing save and Notepad thinks this is Ansi.
